[build]
  command = "npm install -g vite && npm install --prefix Frontend && echo 'Frontend dependencies installed' && npm install --prefix backend && echo 'Backend dependencies installed' && npm run build --prefix Frontend && echo 'Frontend build completed' && npm run build --prefix backend && echo 'Backend build completed'"
  publish = "Frontend/dist"

[context.production.environment]
  NODE_ENV = "production"
  APIChatID = "32ca57aa-c888-4dba-8647-03a908cbfc2c"
  API_ChatEngine = "a18b698d-9c5e-4466-b7a8-aecb1fd19a26"
  Rafshan = "Rafshan"

[functions]
  directory = "netlify/functions"
